insert into tasks (description, completed) values ('Quick and easy side dish with buttery flavor.', 1);
insert into tasks (description, completed) values ('Wireless headphones with noise-canceling features.', 0);
insert into tasks (description, completed) values ('Spicy ginger cookies that are crunchy and delicious.', 1);
insert into tasks (description, completed) values ('A selection of different flavored hummus, great for snacking.', 1);
insert into tasks (description, completed) values ('Set of decorative ceramic planters for indoor plants.', 1);
insert into tasks (description, completed) values ('Freshly roasted coffee beans with rich flavor.', 0);
insert into tasks (description, completed) values ('All-natural skincare set for daily use.', 0);
insert into tasks (description, completed) values ('Just add water for a hearty cheese and broccoli soup in minutes.', 0);
insert into tasks (description, completed) values ('A delicious creamy dip featuring spinach and artichokes, perfect for parties.', 1);
insert into tasks (description, completed) values ('Deliciously creamy almond milk, perfect for smoothies.', 0);
insert into tasks (description, completed) values ('A pre-packaged salad kit with noodles and Asian-style dressing.', 0);
insert into tasks (description, completed) values ('A sleek leather wallet that combines style and functionality.', 0);
insert into tasks (description, completed) values ('Trendy high-top canvas sneakers for a stylish streetwear look.', 0);
insert into tasks (description, completed) values ('Rich spaghetti sauce, a perfect pasta sauce.', 1);
insert into tasks (description, completed) values ('High-resolution camera for stunning photos.', 0);
insert into tasks (description, completed) values ('Space-saving solution to store shoes and keep them organized.', 0);
insert into tasks (description, completed) values ('Soft cookies made with almond butter', 1);
insert into tasks (description, completed) values ('Durable backpack with ample storage for outdoor adventures.', 0);
insert into tasks (description, completed) values ('Soft pita bread, perfect for sandwiches or dips.', 0);
insert into tasks (description, completed) values ('Miso paste for making traditional Japanese miso soup.', 1);
insert into tasks (description, completed) values ('Juicy and tender boneless chicken breasts.', 0);
insert into tasks (description, completed) values ('Wax warmer for creating a soothing atmosphere with fragrances.', 0);
insert into tasks (description, completed) values ('Tablet for digital drawing and illustration work.', 1);
insert into tasks (description, completed) values ('Stay warm with this stylish knit beanie in various colors.', 0);
insert into tasks (description, completed) values ('Pure and natural honey, great for sweetening.', 0);
insert into tasks (description, completed) values ('Savory wraps with buffalo chicken and fresh vegetables.', 0);
insert into tasks (description, completed) values ('Heavy-duty rake with adjustable width for different gardening needs.', 0);
insert into tasks (description, completed) values ('Compact yoga mat that folds for easy storage and transport.', 1);
insert into tasks (description, completed) values ('Quick and easy fried rice mixed with vegetables and soy sauce.', 0);
insert into tasks (description, completed) values ('Complete kit for growing herbs indoors.', 0);
insert into tasks (description, completed) values ('A creamy pumpkin soup with a blend of warm spices, ready to heat and serve.', 1);
insert into tasks (description, completed) values ('Essential oil blends for a soothing atmosphere in your home.', 1);
insert into tasks (description, completed) values ('A pack of assorted nut and protein bars for a quick energy boost.', 0);
insert into tasks (description, completed) values ('Just add water for a hearty cheese and broccoli soup in minutes.', 1);
insert into tasks (description, completed) values ('A warm and sustainable wool scarf for chilly days.', 0);
insert into tasks (description, completed) values ('Complete crafting kit for kids and adults.', 1);
insert into tasks (description, completed) values ('A mix to create a delicious onion dip for parties or snacking.', 0);
insert into tasks (description, completed) values ('A hearty soup made with organic lentils and vegetables.', 1);
insert into tasks (description, completed) values ('Mix to create a delicious chia seed pudding in just a few minutes.', 1);
insert into tasks (description, completed) values ('Personalize your calendar with photos and special dates.', 1);
insert into tasks (description, completed) values ('Lightweight water filter for outdoor adventures.', 1);
insert into tasks (description, completed) values ('Powerful hand blender for soups and smoothies.', 1);
insert into tasks (description, completed) values ('Powerful blender for smoothies and soups.', 1);
insert into tasks (description, completed) values ('Soft oatmeal cookies with maple and pecans.', 0);
insert into tasks (description, completed) values ('Frozen zucchini slices coated in parmesan cheese, perfect for baking or frying.', 0);
insert into tasks (description, completed) values ('Refreshing tea with honey and lemon flavor, perfect for a warm drink.', 0);
insert into tasks (description, completed) values ('Convenient feeder that adjusts to your pet''s height.', 0);
insert into tasks (description, completed) values ('Stainless steel travel mug that keeps drinks hot or cold.', 0);
insert into tasks (description, completed) values ('Fudgy brownie bites, perfect for sharing or snacking.', 1);
insert into tasks (description, completed) values ('High-performance mechanical keyboard with customizable RGB.', 1);
insert into tasks (description, completed) values ('Compact laundry bag for travel use.', 0);
insert into tasks (description, completed) values ('Easy-to-set-up picnic table for outdoor dining.', 1);
insert into tasks (description, completed) values ('Bright flashlight with rechargeable batteries included.', 1);
insert into tasks (description, completed) values ('Refreshing apple juice, 100% juice with no added sugar.', 1);
insert into tasks (description, completed) values ('Refreshing cranberry juice with no added sugar.', 1);
insert into tasks (description, completed) values ('Activity workbook for early learning and fun.', 0);
insert into tasks (description, completed) values ('A creamy blend of avocados and lime juice, great for spreads or dips.', 1);
insert into tasks (description, completed) values ('Love-themed molds for creating desserts and treats.', 0);
insert into tasks (description, completed) values ('Spicy jalapenos stuffed with cheese, ideal for appetizers.', 0);
insert into tasks (description, completed) values ('Compact hand mixer for easy baking.', 0);
insert into tasks (description, completed) values ('High-quality leather wallet with multiple compartments.', 0);
insert into tasks (description, completed) values ('Delicious pie filled with coconut cream and topped with whipped cream.', 0);
insert into tasks (description, completed) values ('Tender ribs smothered in a honey barbecue sauce.', 0);
insert into tasks (description, completed) values ('Durable yoga strap for deeper stretches.', 0);
insert into tasks (description, completed) values ('Refreshing sparkling water with cucumber and lime flavor.', 0);
insert into tasks (description, completed) values ('A delicious tart filled with fresh raspberry filling.', 1);
insert into tasks (description, completed) values ('Leak-proof bottles for travel-sized toiletries.', 1);
insert into tasks (description, completed) values ('Ready-to-eat beet salad with dressing, great side dish.', 1);
insert into tasks (description, completed) values ('Powerful grinder for making sausage and burgers at home.', 1);
insert into tasks (description, completed) values ('Individually packaged bars made with dried fruits and nuts.', 0);
insert into tasks (description, completed) values ('Stylish wine rack to store and display bottles.', 0);
insert into tasks (description, completed) values ('Dimmable LED desk lamp with USB charging port.', 0);
insert into tasks (description, completed) values ('64GB SD memory card for cameras and devices.', 1);
insert into tasks (description, completed) values ('Stylish tote to keep wine bottles chilled while traveling.', 1);
insert into tasks (description, completed) values ('Synthetic crab meat sticks, great for salads and sushi.', 1);
insert into tasks (description, completed) values ('Battery-operated motion sensor light for safety.', 1);
insert into tasks (description, completed) values ('Stylish ripped boyfriend jeans for a relaxed, effortlessly cool vibe.', 0);
insert into tasks (description, completed) values ('Essential tools for bike maintenance and repair.', 0);
insert into tasks (description, completed) values ('Compact and stylish indoor/outdoor fire pit for ambiance.', 0);
insert into tasks (description, completed) values ('Crispy sweet potato fries, a delicious side dish.', 0);
insert into tasks (description, completed) values ('A mix of strawberries, blueberries, and raspberries.', 0);
insert into tasks (description, completed) values ('Bright safety vest for outdoor visibility during any activity.', 1);
insert into tasks (description, completed) values ('Convert your desk to a standing desk easily.', 0);
insert into tasks (description, completed) values ('Creamy Greek yogurt packed with protein and probiotics.', 1);
insert into tasks (description, completed) values ('Delicious and tangy marinade for grilling or baking chicken.', 0);
insert into tasks (description, completed) values ('Healthy pasta alternative made from chickpeas', 1);
insert into tasks (description, completed) values ('Adjustable phone mount for car dashboard.', 1);
insert into tasks (description, completed) values ('Fresh sushi rolls filled with a variety of vegetables.', 0);
insert into tasks (description, completed) values ('Soft cotton graphic tee available in various designs.', 1);
insert into tasks (description, completed) values ('Fresh mango salsa with a hint of lime for a zesty topping.', 0);
insert into tasks (description, completed) values ('Eco-friendly toys for learning and imaginative play.', 1);
insert into tasks (description, completed) values ('Sweet and tart dried cranberries, great for salads and baking.', 0);
insert into tasks (description, completed) values ('Crunchy pretzels dipped in rich dark chocolate.', 0);
insert into tasks (description, completed) values ('Sleek wireless charging pad for smartphones.', 1);
insert into tasks (description, completed) values ('Durable ceramic bakeware for casseroles and desserts.', 1);
insert into tasks (description, completed) values ('Gentle glove for brushing and massaging your pet.', 1);
insert into tasks (description, completed) values ('Comprehensive camera and alert system for home security.', 1);
insert into tasks (description, completed) values ('A classic white button-up shirt for a polished appearance.', 0);
insert into tasks (description, completed) values ('Monthly subscription for freshly roasted coffee delivered to your door.', 0);
insert into tasks (description, completed) values ('Creamy dessert made with rice and cinnamon.', 1);
